[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 300
healthcheckInterval = 45
restartPolicy = "always"
healthcheckProtocol = "http"

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
