# Generated by Django 5.2.3 on 2025-07-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='truck_model',
        ),
        migrations.AddField(
            model_name='engine',
            name='truck_models',
            field=models.ManyToManyField(related_name='engines', to='parts.truckmodel'),
        ),
    ]
