# Generated by Django 5.2.3 on 2025-07-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckmodel',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the truck model', null=True),
        ),
        migrations.AddField(
            model_name='truckmodel',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the truck model', null=True, upload_to='truck_models/'),
        ),
    ]
