# Generated by Django 5.2.3 on 2025-07-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery (COD)'), ('bank_transfer', 'Bank Transfer'), ('installments', 'Installments'), ('mobile_wallet', 'Mobile Wallets')], default='cod', max_length=20),
        ),
    ]
