# Generated by Django 5.2.3 on 2025-08-07 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
