# Generated by Django 5.2.3 on 2025-08-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_remove_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
