# Generated by Django 5.2.3 on 2025-08-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_alter_orderitem_price_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='part',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this part should be available on the website.'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(db_index=True, help_text='Unique identifier for the part', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['session_key', 'added_at'], name='parts_carti_session_46f546_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['name', 'is_active'], name='parts_part_name_29ddba_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['price'], name='parts_part_price_ee5bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['stock'], name='parts_part_stock_3d0b39_idx'),
        ),
    ]
