# Generated by Django 5.2.3 on 2025-08-10 03:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_alter_cartitem_added_at_alter_cartitem_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='partimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image of the truck model', max_length=255, null=True, verbose_name='image'),
        ),
    ]
