# Generated by Django 5.2.3 on 2025-08-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_alter_part_image_alter_partimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image_url',
            field=models.URLField(blank=True, help_text="Alternative external image URL if you don't want to upload an image directly", max_length=1000, null=True),
        ),
    ]
