# Generated by Django 5.2.3 on 2025-08-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_part_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckmodel',
            name='image_url',
            field=models.URLField(blank=True, help_text="Alternative external image URL if you don't want to upload an image directly", max_length=1000, null=True),
        ),
    ]
