# Generated by Django 5.2.3 on 2025-08-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_truckmodel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='partimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL', max_length=1000, null=True),
        ),
    ]
